-- TikGate Stadium E-Ticketing System Schema
-- Simplified for Oracle Database 23ai using Sequences

-- Drop existing objects
BEGIN
   FOR r IN (SELECT sequence_name FROM user_sequences) LOOP
      EXECUTE IMMEDIATE 'DROP SEQUENCE ' || r.sequence_name;
   END LOOP;
   FOR r IN (SELECT table_name FROM user_tables) LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || r.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Create Sequences
CREATE SEQUENCE ROLE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CATEGORY_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TOURNAMENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE EVENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEAT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE BOOKING_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE BOOKING_ITEM_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PAYMENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TICKET_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE VERIFICATION_SEQ START WITH 1 INCREMENT BY 1;

-- Create Tables
CREATE TABLE ROLE (
    ROLE_ID NUMBER PRIMARY KEY,
    ROLE_NAME VARCHAR2(50)
);

CREATE TABLE USERS (
    USER_ID NUMBER PRIMARY KEY,
    ROLE_ID NUMBER,
    USERNAME VARCHAR2(50) UNIQUE,
    PASSWORD VARCHAR2(255) NOT NULL,
    FULL_NAME VARCHAR2(100),
    EMAIL VARCHAR2(100) UNIQUE,
    PHONE VARCHAR2(20),
    CONSTRAINT fk_user_role FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID)
);

CREATE TABLE CATEGORY (
    CATEGORY_ID NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(100),
    DESCRIPTION VARCHAR2(255)
);

CREATE TABLE TOURNAMENT (
    TOURNAMENT_ID NUMBER PRIMARY KEY,
    TOURNAMENT_NAME VARCHAR2(100),
    DESCRIPTION VARCHAR2(255),
    CATEGORY_ID NUMBER,
	CONSTRAINT FK_TOURNAMENT_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
);

CREATE TABLE EVENT (
    EVENT_ID NUMBER PRIMARY KEY,
    TOURNAMENT_ID NUMBER,
    EVENT_NAME VARCHAR2(100),
    EVENT_DATE DATE,
    START_TIME VARCHAR2(20),
    END_TIME VARCHAR2(20),
    DESCRIPTION VARCHAR2(255),
    STATUS VARCHAR2(20),
    CONSTRAINT fk_event_tour FOREIGN KEY (TOURNAMENT_ID) REFERENCES TOURNAMENT(TOURNAMENT_ID)
);

CREATE TABLE SEAT (
    SEAT_ID NUMBER PRIMARY KEY,
    SECTION_NAME VARCHAR2(50),
    ROW_NO VARCHAR2(10),
    SEAT_NUMBER VARCHAR2(10)
);

CREATE TABLE BOOKING (
    BOOKING_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER,
    EVENT_ID NUMBER,
    BOOKING_DATE DATE,
    TOTAL_AMOUNT NUMBER(10,2),
    STATUS VARCHAR2(20),
    CONSTRAINT fk_book_user FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT fk_book_event FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID)
);

CREATE TABLE BOOKING_ITEM (
    BOOKING_ITEM_ID NUMBER PRIMARY KEY,
    BOOKING_ID NUMBER,
    SEAT_ID NUMBER,
    PRICE NUMBER(10,2),
    CONSTRAINT fk_bi_book FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING(BOOKING_ID),
    CONSTRAINT fk_bi_seat FOREIGN KEY (SEAT_ID) REFERENCES SEAT(SEAT_ID)
);

CREATE TABLE PAYMENT (
    PAYMENT_ID NUMBER PRIMARY KEY,
    BOOKING_ID NUMBER,
    PAYMENT_DATE DATE,
    PAYMENT_METHOD VARCHAR2(50),
    AMOUNT NUMBER(10,2),
    PAYMENT_STATUS VARCHAR2(20),
    CONSTRAINT fk_pay_book FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING(BOOKING_ID)
);

CREATE TABLE TICKET (
    TICKET_ID NUMBER PRIMARY KEY,
    BOOKING_ITEM_ID NUMBER,
    QR_CODE VARCHAR2(255),
    PDF_FILE VARCHAR2(255),
    GENERATED_DATE DATE,
    STATUS VARCHAR2(20),
    CONSTRAINT fk_ticket_bi FOREIGN KEY (BOOKING_ITEM_ID) REFERENCES BOOKING_ITEM(BOOKING_ITEM_ID)
);

CREATE TABLE TICKET_VERIFICATION (
    VERIFICATION_ID NUMBER PRIMARY KEY,
    TICKET_ID NUMBER,
    VERIFIED_BY NUMBER,
    VERIFIED_DATE DATE,
    RESULT VARCHAR2(20),
    CONSTRAINT fk_tv_ticket FOREIGN KEY (TICKET_ID) REFERENCES TICKET(TICKET_ID),
    CONSTRAINT fk_tv_staff FOREIGN KEY (VERIFIED_BY) REFERENCES USERS(USER_ID)
);
