-- TikGate Stadium E-Ticketing System Schema
-- Simplified for Oracle Database 23ai using Sequences

-- Drop existing objects
BEGIN
   FOR r IN (SELECT sequence_name FROM user_sequences) LOOP
      EXECUTE IMMEDIATE 'DROP SEQUENCE ' || r.sequence_name;
   END LOOP;
   FOR r IN (SELECT table_name FROM user_tables) LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || r.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Create Sequences
CREATE SEQUENCE ROLE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CATEGORY_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TOURNAMENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE EVENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEAT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE BOOKING_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE BOOKING_ITEM_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PAYMENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TICKET_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE VERIFICATION_SEQ START WITH 1 INCREMENT BY 1;

-- Create Tables
CREATE TABLE ROLE (
    ROLE_ID NUMBER PRIMARY KEY,
    ROLE_NAME VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE USERS (
    USER_ID NUMBER PRIMARY KEY,
    ROLE_ID NUMBER NOT NULL,
    USERNAME VARCHAR2(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(255) NOT NULL,
    FULL_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    PHONE VARCHAR2(20) NOT NULL,
    CONSTRAINT chk_user_phone CHECK (REGEXP_LIKE(PHONE, '^[0-9]{10,15}$')),
    CONSTRAINT chk_user_role CHECK (ROLE_ID IN (1, 2, 3)),
    CONSTRAINT fk_user_role FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID)
);

CREATE TABLE CATEGORY (
    CATEGORY_ID NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(100) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR2(255)
);

CREATE TABLE TOURNAMENT (
    TOURNAMENT_ID NUMBER PRIMARY KEY,
    TOURNAMENT_NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(255),
    CATEGORY_ID NUMBER NOT NULL,
    CONSTRAINT uk_tournament_category_name UNIQUE (CATEGORY_ID, TOURNAMENT_NAME),
	CONSTRAINT FK_TOURNAMENT_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
);

CREATE TABLE EVENT (
    EVENT_ID NUMBER PRIMARY KEY,
    TOURNAMENT_ID NUMBER NOT NULL,
    EVENT_NAME VARCHAR2(100) NOT NULL,
    EVENT_DATE DATE NOT NULL,
    START_TIME VARCHAR2(20) NOT NULL,
    END_TIME VARCHAR2(20) NOT NULL,
    DESCRIPTION VARCHAR2(255),
    STATUS VARCHAR2(20) NOT NULL,
    CONSTRAINT chk_event_status CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'CANCELLED')),
    CONSTRAINT chk_event_start_time CHECK (REGEXP_LIKE(START_TIME, '^([01][0-9]|2[0-3]):[0-5][0-9]$')),
    CONSTRAINT chk_event_end_time CHECK (REGEXP_LIKE(END_TIME, '^([01][0-9]|2[0-3]):[0-5][0-9]$')),
    CONSTRAINT chk_event_time CHECK (END_TIME > START_TIME),
    CONSTRAINT uk_event_tournament_name_date UNIQUE (TOURNAMENT_ID, EVENT_NAME, EVENT_DATE),
    CONSTRAINT fk_event_tour FOREIGN KEY (TOURNAMENT_ID) REFERENCES TOURNAMENT(TOURNAMENT_ID)
);

CREATE TABLE SEAT (
    SEAT_ID NUMBER PRIMARY KEY,
    SECTION_NAME VARCHAR2(50) NOT NULL,
    ROW_NO VARCHAR2(10) NOT NULL,
    SEAT_NUMBER VARCHAR2(10) NOT NULL,
    CONSTRAINT chk_seat_row CHECK (REGEXP_LIKE(ROW_NO, '^[A-Za-z0-9]{1,10}$')),
    CONSTRAINT chk_seat_number CHECK (REGEXP_LIKE(SEAT_NUMBER, '^[0-9]{1,4}$')),
    CONSTRAINT uk_seat_location UNIQUE (SECTION_NAME, ROW_NO, SEAT_NUMBER)
);

CREATE TABLE BOOKING (
    BOOKING_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    EVENT_ID NUMBER NOT NULL,
    BOOKING_DATE DATE NOT NULL,
    TOTAL_AMOUNT NUMBER(10,2) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    CONSTRAINT chk_booking_amount CHECK (TOTAL_AMOUNT > 0),
    CONSTRAINT chk_booking_status CHECK (STATUS IN ('PENDING', 'PAID', 'CANCELLED')),
    CONSTRAINT fk_book_user FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT fk_book_event FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID)
);

CREATE TABLE BOOKING_ITEM (
    BOOKING_ITEM_ID NUMBER PRIMARY KEY,
    BOOKING_ID NUMBER NOT NULL,
    EVENT_ID NUMBER NOT NULL,
    SEAT_ID NUMBER NOT NULL,
    PRICE NUMBER(10,2) NOT NULL,
    CONSTRAINT chk_bi_price CHECK (PRICE > 0),
    CONSTRAINT uk_event_seat UNIQUE (EVENT_ID, SEAT_ID),
    CONSTRAINT fk_bi_book FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING(BOOKING_ID),
    CONSTRAINT fk_bi_event FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID),
    CONSTRAINT fk_bi_seat FOREIGN KEY (SEAT_ID) REFERENCES SEAT(SEAT_ID)
);

CREATE TABLE PAYMENT (
    PAYMENT_ID NUMBER PRIMARY KEY,
    BOOKING_ID NUMBER NOT NULL UNIQUE,
    PAYMENT_DATE DATE NOT NULL,
    PAYMENT_METHOD VARCHAR2(50) NOT NULL,
    AMOUNT NUMBER(10,2) NOT NULL,
    PAYMENT_STATUS VARCHAR2(20) NOT NULL,
    CONSTRAINT chk_payment_amount CHECK (AMOUNT > 0),
    CONSTRAINT chk_payment_method CHECK (PAYMENT_METHOD IN ('Credit Card', 'Online Banking', 'E-Wallet')),
    CONSTRAINT chk_payment_status CHECK (PAYMENT_STATUS IN ('SUCCESS', 'FAILED')),
    CONSTRAINT fk_pay_book FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING(BOOKING_ID)
);

CREATE TABLE TICKET (
    TICKET_ID NUMBER PRIMARY KEY,
    BOOKING_ITEM_ID NUMBER NOT NULL UNIQUE,
    QR_CODE VARCHAR2(255) NOT NULL UNIQUE,
    PDF_FILE VARCHAR2(255),
    GENERATED_DATE DATE NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    CONSTRAINT chk_ticket_qr CHECK (REGEXP_LIKE(QR_CODE, '^[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}$')),
    CONSTRAINT chk_ticket_status CHECK (STATUS IN ('VALID', 'USED', 'INVALID')),
    CONSTRAINT fk_ticket_bi FOREIGN KEY (BOOKING_ITEM_ID) REFERENCES BOOKING_ITEM(BOOKING_ITEM_ID)
);

CREATE TABLE TICKET_VERIFICATION (
    VERIFICATION_ID NUMBER PRIMARY KEY,
    TICKET_ID NUMBER,
    VERIFIED_BY NUMBER NOT NULL,
    VERIFIED_DATE DATE NOT NULL,
    RESULT VARCHAR2(20) NOT NULL,
    CONSTRAINT chk_tv_result CHECK (RESULT IN ('SUCCESS', 'FAILED')),
    CONSTRAINT fk_tv_ticket FOREIGN KEY (TICKET_ID) REFERENCES TICKET(TICKET_ID),
    CONSTRAINT fk_tv_staff FOREIGN KEY (VERIFIED_BY) REFERENCES USERS(USER_ID)
);
