-- Roles
INSERT INTO ROLE (ROLE_ID, ROLE_NAME) VALUES (ROLE_SEQ.NEXTVAL, 'ADMIN');
INSERT INTO ROLE (ROLE_ID, ROLE_NAME) VALUES (ROLE_SEQ.NEXTVAL, 'CUSTOMER');
INSERT INTO ROLE (ROLE_ID, ROLE_NAME) VALUES (ROLE_SEQ.NEXTVAL, 'STAFF');

-- Users
INSERT INTO USERS (USER_ID, ROLE_ID, USERNAME, PASSWORD, FULL_NAME, EMAIL, PHONE) VALUES 
(USER_SEQ.NEXTVAL, 1, 'admin', 'admin123', 'System Administrator', 'admin@tikgate.com', '0123456789');
INSERT INTO USERS (USER_ID, ROLE_ID, USERNAME, PASSWORD, FULL_NAME, EMAIL, PHONE) VALUES 
(USER_SEQ.NEXTVAL, 2, 'customer', 'cust123', 'John Doe', 'john@example.com', '0112233445');
INSERT INTO USERS (USER_ID, ROLE_ID, USERNAME, PASSWORD, FULL_NAME, EMAIL, PHONE) VALUES 
(USER_SEQ.NEXTVAL, 3, 'staff', 'staff123', 'Staff Member', 'staff@tikgate.com', '0198765432');

-- Categories
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, DESCRIPTION) VALUES 
(CATEGORY_SEQ.NEXTVAL, 'Football', 'Soccer matches');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, DESCRIPTION) VALUES 
(CATEGORY_SEQ.NEXTVAL, 'Basketball', 'Basketball tournaments');

-- Tournaments
INSERT INTO TOURNAMENT (TOURNAMENT_ID, CATEGORY_ID, TOURNAMENT_NAME, DESCRIPTION) VALUES 
(TOURNAMENT_SEQ.NEXTVAL, 1, 'Champions League', 'European club football');
INSERT INTO TOURNAMENT (TOURNAMENT_ID, CATEGORY_ID, TOURNAMENT_NAME, DESCRIPTION) VALUES 
(TOURNAMENT_SEQ.NEXTVAL, 2, 'NBA', 'National Basketball Association');

-- Events
INSERT INTO EVENT (EVENT_ID, TOURNAMENT_ID, EVENT_NAME, EVENT_DATE, START_TIME, END_TIME, DESCRIPTION, STATUS) VALUES 
(EVENT_SEQ.NEXTVAL, 1, 'Champions League Final', TO_DATE('2026-07-15', 'YYYY-MM-DD'), '20:00', '22:30', 'The biggest match of the season', 'ACTIVE');
INSERT INTO EVENT (EVENT_ID, TOURNAMENT_ID, EVENT_NAME, EVENT_DATE, START_TIME, END_TIME, DESCRIPTION, STATUS) VALUES 
(EVENT_SEQ.NEXTVAL, 2, 'NBA Finals Game 1', TO_DATE('2026-06-20', 'YYYY-MM-DD'), '19:00', '21:30', 'Championship basketball', 'ACTIVE');

-- Seats
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'North', 'A', '1');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'North', 'A', '2');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'North', 'A', '3');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'North', 'A', '4');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'North', 'A', '5');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'North', 'B', '1');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'North', 'B', '2');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'North', 'B', '3');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'North', 'B', '4');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'North', 'B', '5');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'South', 'A', '1');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'South', 'A', '2');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'South', 'A', '3');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'South', 'A', '4');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'South', 'A', '5');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'South', 'B', '1');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'South', 'B', '2');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'South', 'B', '3');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'South', 'B', '4');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'South', 'B', '5');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'East', 'A', '1');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'East', 'A', '2');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'East', 'A', '3');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'East', 'A', '4');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'East', 'A', '5');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'East', 'B', '1');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'East', 'B', '2');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'East', 'B', '3');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'East', 'B', '4');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'East', 'B', '5');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'East', 'C', '1');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'East', 'C', '2');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'East', 'C', '3');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'East', 'C', '4');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'East', 'C', '5');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'East', 'D', '1');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'East', 'D', '2');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'East', 'D', '3');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'East', 'D', '4');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'East', 'D', '5');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'West', 'A', '1');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'West', 'A', '2');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'West', 'A', '3');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'West', 'A', '4');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'West', 'A', '5');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'West', 'B', '1');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'West', 'B', '2');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'West', 'B', '3');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'West', 'B', '4');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'West', 'B', '5');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'West', 'C', '1');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'West', 'C', '2');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'West', 'C', '3');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'West', 'C', '4');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'West', 'C', '5');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'West', 'D', '1');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'West', 'D', '2');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'West', 'D', '3');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'West', 'D', '4');
INSERT INTO SEAT (SEAT_ID, SECTION_NAME, ROW_NO, SEAT_NUMBER) VALUES (SEAT_SEQ.NEXTVAL, 'West', 'D', '5');

COMMIT;
